apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sre-copilot
resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: sre-copilot-code
    files:
      - copilot.py
