apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-copilot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/allena9/cse499-gitops.git
    targetRevision: main
    path: manifests/sre-copilot
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-copilot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
